apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  resources:
    requests:
      storage: 140Gi
  storageClassName: nfs-immich
  accessModes:
    - ReadWriteOnce
