---
all:
  children:
    k3s_servers:
      hosts:
        k3s-server-1:
          ansible_host: 10.0.0.150
    k3s_agents:
      hosts:
        k3s-agent-1:
          ansible_host: 10.0.0.151
        k3s-agent-2:
          ansible_host: 10.0.0.152
    k3s_nodes:
      children:
        k3s_servers:
        k3s_agents:
      vars:
        ansible_user: ubuntu
        ansible_become: true
    lxcs:
      hosts:
        pihole:
          ansible_host: 10.0.0.160
        media:
          ansible_host: 10.0.0.161
        ollama:
          ansible_host: 10.0.0.162
        hermes:
          ansible_host: 10.0.0.163
      vars:
        ansible_user: root
        ansible_become: false
